# Generated by Django 4.2.1 on 2023-05-13 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_client_createdby_remove_client_updatedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.BooleanField(default=True)),
                ('createdOn', models.DateTimeField(blank=True, null=True)),
                ('updatedOn', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='app.client')),
            ],
        ),
    ]
