# Generated by Django 4.2.1 on 2023-05-15 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_purchaseorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('invNo', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emailDate', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('createdOn', models.DateTimeField(blank=True, null=True)),
                ('updatedOn', models.DateTimeField(blank=True, null=True)),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice', to='app.quotation')),
            ],
        ),
    ]
