# Generated by Django 4.2.1 on 2023-05-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_deliveryorder_quotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
